[project]
name = "personal-intern"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.39.0",
    "pydantic>=2.10.3",
    "scrapybara>=0.2.2",
    "typer>=0.15.1",
]
